name: Run hello-word py script
on: push

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
    - name: Clone Repo
      uses: actions/checkout@v7
    
    - name: Install python
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'

    - name: Run hello-world python program
      run: python hello.py
