name: Run hello world from py script
on: push

jobs:
    Hello:
        runs-on: ubuntu-latest

        steps:
        - name: Clone repo
        - uses: actions/checkout@v7

        - name: Setup python
        - uses: actions/setup-python@v6
          with:
            python-version: '3.13' 

        - name: Run python script
          run: python hello.py